# Generated by Django 5.2.4 on 2025-07-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sale_price_sale_product_sale_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
    ]
