# Generated by Django 5.2.4 on 2025-07-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_sale_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bulk_product',
            field=models.BooleanField(default=False, help_text='Product is sold in boxes/cases'),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_box',
            field=models.PositiveIntegerField(default=1, help_text='Number of units in one box/case'),
        ),
    ]
